### ISSUE TITLE
Fails to start on Amazon Linux 2 

### ISSUE THREAD

**Issue by hmijail** [INFURA/devp2p-network#32]
I'm an NPM newbie, so if more info is needed please let me know.

```
$ npm start

> devp2p-network@1.0.0 start /home/ec2-user/devp2p_walk/devp2p-network
> INFURA_ID=09bcdf3656ee4a80b05a4a921358d109 node index.js

/home/ec2-user/devp2p_walk/devp2p-network/node_modules/web3-core-method/src/index.js:292
                .then(async function (receipt) {
                      ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/devp2p_walk/devp2p-network/node_modules/web3-core/src/extend.js:27:14)

npm ERR! Linux 4.14.88-88.73.amzn2.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! devp2p-network@1.0.0 start: `INFURA_ID=09bcdf3656ee4a80b05a4a921358d109 node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the devp2p-network@1.0.0 start script 'INFURA_ID=09bcdf3656ee4a80b05a4a921358d109 node index.js'.
```

$ docker --version
Docker version 19.03.6-ce, build 369ce74
$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9

**Comment by egalano** [comment]
It looks like you are running with node 6.17.1. Please use the latest stable node v12
